# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='image_1',
            field=models.ImageField(null=True, upload_to='profiles/consumers'),
        ),
    ]
