# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_consumer_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='image_2',
            field=models.ImageField(null=True, upload_to='profiles/consumers'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='image_3',
            field=models.ImageField(null=True, upload_to='profiles/consumers'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='image_4',
            field=models.ImageField(null=True, upload_to='profiles/consumers'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='image_5',
            field=models.ImageField(null=True, upload_to='profiles/consumers'),
        ),
    ]
