# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170610_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='boc_acc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='boc_acc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/consumers'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/consumers'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/consumers'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/consumers'),
        ),
    ]
