# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_consumer_image_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image_1', models.FileField(upload_to='pos/snaps/')),
                ('url', models.URLField(null=True)),
                ('recognized_user_id', models.TextField(blank=True, max_length=500)),
                ('recognition_successful', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Vendor')),
            ],
        ),
    ]
