# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facing', '0004_auto_20170610_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='recognized_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paying_uploads', to='profiles.Consumer'),
        ),
    ]
